spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mbplus
    username: rrromanm
    password: ""
    driver-class-name: org.postgresql.Driver
  config:
    import: optional:classpath:application-local-secrets.yaml

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: never

jwt:
  secret: "z3sw89ZmSrp1LuNfmu1KFIWxlznf0OX4ef+F72Z5pn4="
  expiration-ms: 1800000

server:
  port: 8080
  forward-headers-strategy: framework

app:
  cookie:
    secure: false
    same-site: "Strict"

cloudinary:
  folder: mbplus/local

